// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { DATA_PROVIDER, IS_STUDIO_MODE, USE_MOCK_DATA_PROVIDER } from '@/config/runtime';
import { createMockSupabaseClient } from './mockClient';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const hasSupabaseCredentials = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
const shouldUseMockClient = USE_MOCK_DATA_PROVIDER || !hasSupabaseCredentials;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (shouldUseMockClient) {
  const reason = !hasSupabaseCredentials ? "missing Supabase credentials" : `provider=${DATA_PROVIDER}`;
  // eslint-disable-next-line no-console
  console.info(`[runtime] Using mock data client (${reason}). studio=${IS_STUDIO_MODE}`);
}

export const supabase: any = shouldUseMockClient
  ? createMockSupabaseClient()
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
